channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=0.30.6=py27_0
  - jupyterlab_launcher=0.6.0=py27_0
  - _tflow_190_select=0.0.3=mkl
  - absl-py=0.3.0=py27_0
  - asn1crypto=0.23.0=py27h7b0c810_0
  - astor=0.7.1=py27_0
  - backports=1.0=py27h63c9359_1
  - backports.functools_lru_cache=1.4=py27he8db605_1
  - backports.shutil_get_terminal_size=1.0.0=py27h5bc021e_2
  - backports.weakref=1.0.post1=py27_0
  - backports_abc=0.5=py27h7b3c97b_0
  - blas=1.0=mkl
  - bleach=2.1.1=py27h655ea9b_0
  - bokeh=0.13.0=py27_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py27_0
  - cffi=1.11.2=py27ha7929c6_0
  - chardet=3.0.4=py27hfa10054_1
  - click=6.7=py27h4225b90_0
  - cloudpickle=0.5.2=py27hc3dac03_0
  - conda=4.5.9=py27_0
  - conda-env=2.6.0=h36134e3_1
  - configparser=3.5.0=py27h5117587_0
  - cryptography=2.1.4=py27h6697b16_0
  - cycler=0.10.0=py27hc7354d3_0
  - cytoolz=0.9.0.1=py27h14c3975_1
  - dask=0.18.2=py27_0
  - dask-core=0.18.2=py27_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.1.2=py27h1544723_0
  - distributed=1.22.0=py27_0
  - entrypoints=0.2.3=py27h502b47d_2
  - enum34=1.1.6=py27h99a27e9_1
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_0
  - funcsigs=1.0.2=py27_0
  - functools32=3.2.3.2=py27h4ead58f_1
  - futures=3.2.0=py27h7b459c0_0
  - gast=0.2.0=py27_0
  - glib=2.56.1=h000015b_0
  - gmp=6.1.2=h6c8ec71_1
  - grpcio=1.12.1=py27hdbcaa40_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py27h8d01980_0
  - hdf5=1.10.2=hba1933b_1
  - heapdict=1.0.0=py27h33770af_0
  - html5lib=1.0.1=py27h5233db4_0
  - icu=58.2=h9c2bf20_1
  - idna=2.6=py27h5722d68_1
  - imageio=2.3.0=py27_0
  - intel-openmp=2018.0.0=hc7b2577_8
  - ipaddress=1.0.18=py27h337fd85_0
  - ipykernel=4.7.0=py27h5233db4_0
  - ipython=5.4.1=py27h36c99b6_1
  - ipython_genutils=0.2.0=py27h89fb69b_0
  - ipywidgets=7.0.5=py27hfb35cc2_0
  - jinja2=2.10=py27h4114e70_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py27h7ed5aa4_0
  - jupyter=1.0.0=py27h505fd4b_0
  - jupyter_client=5.1.0=py27hbee1118_0
  - jupyter_console=5.2.0=py27hc6bee7e_1
  - jupyter_core=4.4.0=py27h345911c_0
  - kiwisolver=1.0.1=py27hf484d3e_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libpng=1.6.34=hb9fc6fc_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libsodium=1.0.15=hf101ebd_0
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libtiff=4.0.9=h28f6b97_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=hf84eae3_0
  - linecache2=1.0.0=py27_0
  - locket=0.2.0=py27h73929a2_1
  - markdown=2.6.11=py27_0
  - markupsafe=1.0=py27h97b2822_1
  - matplotlib=2.2.2=py27hb69df0a_2
  - mistune=0.8.1=py27h1bd0165_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py27h4414c95_1
  - mkl_random=1.0.1=py27h4414c95_1
  - mock=2.0.0=py27h0c0c831_0
  - msgpack-python=0.4.8=py27hc2fa789_0
  - nbconvert=5.3.1=py27he041f76_0
  - nbformat=4.4.0=py27hed7f2b2_0
  - ncurses=6.0=h9df7e31_2
  - networkx=2.0=py27hfc23926_0
  - nodejs=6.11.2=h3db8ef7_0
  - notebook=5.2.2=py27h6748267_0
  - numpy=1.15.0=py27h1b885b7_0
  - numpy-base=1.15.0=py27h3dfced4_0
  - olefile=0.44=py27h4bd3e3c_0
  - openssl=1.0.2o=h20670df_0
  - packaging=17.1=py27_0
  - pandas=0.23.3=py27h04863e7_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py27h428e1e5_1
  - partd=0.3.8=py27h4e55004_0
  - pathlib2=2.3.0=py27h6e9d198_0
  - pbr=4.2.0=py27_0
  - pcre=8.42=h439df22_0
  - pexpect=4.3.0=py27hdeba8d9_0
  - pickleshare=0.7.4=py27h09770e1_0
  - pillow=5.2.0=py27heded4f4_0
  - pip=9.0.1=py27ha730c48_4
  - prompt_toolkit=1.0.15=py27h1b593e1_0
  - protobuf=3.5.2=py27hf484d3e_1
  - psutil=5.4.1=py27h61c8946_0
  - ptyprocess=0.5.2=py27h4ccb14c_0
  - pycosat=0.6.3=py27ha4109ae_0
  - pycparser=2.18=py27hefa08c5_1
  - pygments=2.2.0=py27h4a8b6f5_0
  - pyopenssl=17.5.0=py27hcee3be0_0
  - pyparsing=2.2.0=py27hf1513f8_1
  - pyqt=5.9.2=py27h22d08a2_0
  - pysocks=1.6.7=py27he2db6d2_1
  - python=2.7.14=h1571d57_29
  - python-dateutil=2.6.1=py27h4ca5741_1
  - pytz=2017.3=py27h001bace_0
  - pywavelets=0.5.2=py27h035aef0_2
  - pyyaml=3.12=py27h2d70dd7_1
  - pyzmq=16.0.3=py27hc579512_0
  - qt=5.9.6=h52aff34_0
  - qtconsole=4.3.1=py27hc444b0d_0
  - readline=7.0=ha6073c6_4
  - requests=2.18.4=py27hc5b0589_1
  - ruamel_yaml=0.11.14=py27h672d447_2
  - scandir=1.6=py27hf7388dc_0
  - scikit-image=0.14.0=py27hf484d3e_1
  - scikit-learn=0.19.1=py27hedc7406_0
  - scipy=1.1.0=py27hc49cb51_0
  - setuptools=36.5.0=py27h68b189e_0
  - simplegeneric=0.8.1=py27h19e43cd_0
  - singledispatch=3.4.0.3=py27h9bcb476_0
  - sip=4.19.8=py27hf484d3e_0
  - six=1.11.0=py27h5f960f1_1
  - sortedcontainers=1.5.7=py27he59936f_0
  - sqlite=3.23.1=he433501_0
  - ssl_match_hostname=3.5.0.1=py27h4ec10b9_2
  - subprocess32=3.2.7=py27h373dbce_0
  - tblib=1.3.2=py27h51fe5ba_0
  - tensorboard=1.9.0=py27hf484d3e_0
  - tensorflow=1.9.0=mkl_py27h0cb61a4_1
  - tensorflow-base=1.9.0=mkl_py27h2ca6a6a_0
  - termcolor=1.1.0=py27_1
  - terminado=0.6=py27h4be8df9_0
  - testpath=0.3.1=py27hc38d2c4_0
  - tk=8.6.7=hc745277_3
  - toolz=0.8.2=py27hd3b1e7e_0
  - tornado=4.5.2=py27h97b179f_0
  - traceback2=1.4.0=py27_0
  - traitlets=4.3.2=py27hd6ce930_0
  - unittest2=1.1.0=py27_0
  - urllib3=1.22=py27ha55213b_0
  - wcwidth=0.1.7=py27h9e3e1ab_0
  - webencodings=0.5.1=py27hff10b21_1
  - werkzeug=0.14.1=py27_0
  - wheel=0.30.0=py27h2bc6bb2_1
  - widgetsnbextension=3.0.8=py27h618a941_0
  - xz=5.2.3=h55aa19d_2
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.2=hbedb6e5_2
  - zict=0.1.3=py27h12c336c_0
  - zlib=1.2.11=ha838bed_2
